### ISSUE TITLE
Installation issue: no wmake

### ISSUE THREAD

**Issue by DeMilder** [ITHACA-FV/ITHACA-FV#471]
Hi, I am new to OpenFOAM, to ROM and also to Github. I would like to try this package out. However, I encountered an installation issue. When I run the last step of the installation instructions:
`sudo ./Allwmake`
(I needed to add sudo to give permissions)
I obtain the error
`Error: no wmake - is OPENFOAM enviroment active?`

Can somebody explain what this error message means and how to tackle it?

Thanks in advance!

**Comment by giovastabile** [comment]
Hi @DeMilder you need to source the openfoam bashrc file and the ithaca-fv bashrc file. In order to avoid using sudo you can clone ITHACA-FV in a folder in which you have permits (in your home for example)

`source your_openfoam_folder/etc/bashrc`
`source your_ithacafolder/etc/bashrc`

after that you can run ./Allwmake as usual
